const ActionTypes = {
    UPDATE_USER: "UPDATE_USER",
    UPDATE_USER_RESPONSE: "UPDATE_USER_RESPONSE",

    GET_USERS_RESPONSE: "GET_USERS_RESPONSE",
    REQ_GET_USERS: "REQ_GET_USERS",
    GET_USERS: "GET_USERS",

    ADD_USER: "ADD_USER",
    ADD_USER_RESPONSE: "ADD_USER_RESPONSE",

    DEL_USER: "DEL_USER",
    DEL_USER_RESPONSE: "DEL_USER_RESPONSE",
    
    
    GET_PRODUCTS: "GET_PRODUCTS",
    GET_PRODUCTS_RESPONSE: "GET_PRODUCTS_RESPONSE",

    ADD_PRODUCT: "ADD_PRODUCT",
    ADD_PRODUCT_RESPONSE: "ADD_PRODUCT_RESPONSE",

    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    UPDATE_PRODUCT_RESPONSE: "UPDATE_PRODUCT_RESPONSE",

    DEL_PRODUCT: "DEL_PRODUCT",

    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_RESPONSE: "LOGIN_RESPONSE",

    GET_PRODUCTS_CATEGORY_REQUEST: "GET_PRODUCTS_CATEGORY_REQUEST",
    GET_PRODUCTS_CATEGORY_RESPONSE: "GET_PRODUCTS_CATEGORY_RESPONSE"
};

export default ActionTypes